### PR TITLE
SLIM-898 bundle request for get profile generic data

### PR DESCRIPTION
**Pull request by smvdheijden**

### CODE REVIEW

**Comment by smvdheijden** [comment]
retest this please

**Comment by riannefijn** [comment]
retest this please

**Comment by riannefijn** [comment]
retest this please

**Comment by riannefijn** [comment]
retest this please

**Comment by riannefijn** [comment]
retest this please

**Comment by riannefijn** [comment]
retest this please

**Comment by riannefijn** [comment]
retest this please

**Pull request merged**
