### PR TITLE
FLEX-2828 ~ Automate regressiontest C151

### PR DESCRIPTION
**Pull request by MartijnSipsCGI**

### CODE REVIEW

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by SamVanDijk** [comment]
retest this please

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by SamVanDijk** [comment]
retest this please

**Comment by SamVanDijk** [comment]
This pull request is taking over by pull request #209, therefor this pull request is closed.

**Pull request closed without merging**
