### PR TITLE
Slim 1148 make daylight savings deviation not writable

### PR DESCRIPTION
**Pull request by robindenadel**

### CODE REVIEW

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by smvdheijden** [comment]
Looks like there are some merging issues, as in the PR some files seem to have been deleted, while they should not have been...

**Comment by smvdheijden** [comment]
Retest this please

**Pull request merged**
