### PR TITLE
SLIM-1225 Fix find events response when no events are found

### PR DESCRIPTION
**Pull request by bjornamkreutz**
Test [@smartmetering]

### CODE REVIEW

**Comment by bjornamkreutz** [comment]
retest this please

**Comment by bjornamkreutz** [comment]
Test only [@smartmetering]

**Comment by bjornamkreutz** [comment]
retest this please

**Comment by bjornamkreutz** [comment]
retest this please

**Comment by bjornamkreutz** [comment]
retest this please

**Comment by bjornamkreutz** [comment]
retest this please

**Comment by smvdheijden** [comment]
retest this please

**Pull request merged**
