### PR TITLE
Flex 3007 Convert ProtocolSequenceNumber fitnesse tests to cucumber

### PR DESCRIPTION
**Pull request by SamVanDijk**

### CODE REVIEW

**Comment by SamVanDijk** [comment]
test this please

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by SamVanDijk** [comment]
retest this please

**Comment by MartijnSipsCGI** [comment]
Retest this please

**Comment by MartijnSipsCGI** [comment]
retest this please

**Comment by SamVanDijk** [comment]
retest this please

**Pull request merged**
